"""Stable, deterministic identity-generation boundary."""

from geno.identity.canonical import canonical_json_bytes, normalize_unicode
from geno.identity.identifiers import (
    IDENTIFIER_SCHEME_VERSION,
    LOCAL_REPOSITORY_IDENTIFIER_SCHEME_VERSION,
    CandidateUnitId,
    EvolutionEdgeId,
    FamilyId,
    GeneId,
    NormalizedUnitId,
    OccurrenceId,
    PipelineRunId,
    RepositoryId,
    SourceFileId,
    VersionId,
    create_candidate_unit_id,
    create_evolution_edge_id,
    create_family_id,
    create_gene_id,
    create_local_repository_id,
    create_normalized_unit_id,
    create_occurrence_id,
    create_pipeline_run_id,
    create_repository_id,
    create_source_file_id,
    create_version_id,
)
from geno.identity.normalization import (
    NormalizedGitRepository,
    normalize_git_repository,
    normalize_relative_path,
    normalize_repository_name,
    normalize_repository_owner,
)

__all__ = [
    "IDENTIFIER_SCHEME_VERSION",
    "LOCAL_REPOSITORY_IDENTIFIER_SCHEME_VERSION",
    "CandidateUnitId",
    "EvolutionEdgeId",
    "FamilyId",
    "GeneId",
    "NormalizedGitRepository",
    "NormalizedUnitId",
    "OccurrenceId",
    "PipelineRunId",
    "RepositoryId",
    "SourceFileId",
    "VersionId",
    "canonical_json_bytes",
    "create_candidate_unit_id",
    "create_evolution_edge_id",
    "create_family_id",
    "create_gene_id",
    "create_local_repository_id",
    "create_normalized_unit_id",
    "create_occurrence_id",
    "create_pipeline_run_id",
    "create_repository_id",
    "create_source_file_id",
    "create_version_id",
    "normalize_git_repository",
    "normalize_relative_path",
    "normalize_repository_name",
    "normalize_repository_owner",
    "normalize_unicode",
]
